---
title: "Vacant Houses in Baltimore"
subtitle: "Coursera, Developing Data Products, R Markdown and Leaflet Assignment (Wk 2)"
author: "J. Allen Baron"
date: "May 7, 2018"
output: 
  html_document: 
    toc: TRUE
    toc_float:
        collapsed: FALSE
---

## Goal
Create an interactive plot to explore the distribution of vacant (_i.e._ boarded up) houses in Baltimore, Maryland, USA.

```{r, include = FALSE}
library(RSocrata)
library(tidyverse)
library(stringr)
library(leaflet)
library(leaflet.extras)
library(sf)
library(htmltools)
```

## Prepare Data
### Load Baltimore vacant (_i.e._ boarded up) houses data
```{r load_data, results = 'hide'}
balt_vacant <- read.socrata("https://data.baltimorecity.gov/resource/rw5h-nvv4.csv")
```

### Tidy location data
```{r, tidy_location, message = FALSE}
location <- str_split(balt_vacant$location, pattern = " ", simplify = TRUE) %>%
    as_tibble()
colnames(location) <- c("location_type", "longitude", "latitude")

location <- purrr::map_dfc(location,
                      ~ str_remove_all(.x, pattern = "\\(|\\)") %>%
                          str_trim(.)
                      ) %>%
            type_convert(.)

balt_vacant <- cbind(balt_vacant, location)
```

### Load Baltimore neighborhood boundaries
To give someone not familiar with Baltimore some context
```{r neighborhood_data}
neighborhoods <- read_sf("https://data.baltimorecity.gov/resource/h3fx-54q3.geojson")
```

## Complete map
```{r complete_map}
leaflet(data = balt_vacant) %>%
    addTiles(.) %>%
    addHeatmap(., lng = ~ longitude, lat = ~ latitude,
               radius = 10,
               minOpacity = 0.5, max = 100
               ) %>%
    addPolygons(., data = neighborhoods,
                color = "black", weight = 1, opacity = 0.5, fillOpacity = 0,
                label = ~ htmlEscape(label)
                )
```

## Session info
```{r}
sessionInfo()
```

